services:
  rocketscreeners:
    build: .
    image: rocketscreenersvitejs:latest
    container_name: rocketscreeners
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - proxy

networks:
  proxy:
    external: true
